### ISSUE TITLE
Change of dependency scope

### ISSUE THREAD

**Issue by echav** [auth0/auth0-java-mvc-common#19]
Hello,

upgrading from 1.0.0 to 1.0.2, the compilation of my code broke because I was using the com.auth0.jwt.JWT class. Looking at the changes, I found that the scope of some dependencies was changed in revision https://github.com/auth0/auth0-java-mvc-common/commit/196c640b3611b413efa336c090083e16c220e5a3#diff-c197962302397baf3a4cc36463dce5ea

In Maven (that I use), this translates into changing the dependency scope from compile to runtime. I assume this is a consequence of moving from "compile" to "implementation" in your build.graddle.

I am not sure why this change was made, or if I am misusing the library. I was for example using in my code the public static method JWT.decode(). Is this something you discourage on purpose?

**Comment by stepbeek** [comment]
From what I can gather from here:

https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

This means that we no longer transitively pick up the dependencies for JWT that are used in the tutorial here:

https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc

Should the tutorial be updated to reflect the new state of this library?

**Comment by stepbeek** [comment]
Any response on this from Auth0? It's pretty disappointing to have a minor version break the library.

**Comment by tedyoung** [comment]
This is broken for me as well. If we're not supposed to depend on com.auth0.jwt.JWT directly, is there an API package that we're supposed to use? This is a blocker.

**Comment by tedyoung** [comment]
Looking more deeply, it appears that the `com.auth0` packages should have been marked as `api` and **not** `implementation`. I am concerned that this issue has been open for so long when it's so clearly broken, does not inspire confidence in the quality of the libraries.

**Comment by lbalmaceda** [comment]
Thanks for raising this, I don't know why I haven't received any GitHub notification. The change we did was replacing the release plugin with one that uses a newer version of Gradle. That made me change the scope from compile to implementation, and I might have mistakenly used a different scope for the jwt dependency. I'll review this the next week and make a new release.
