### ISSUE TITLE
Sessionless version?

### ISSUE THREAD

**Issue by AIMMOTH** [auth0/auth0-java-mvc-common#2]
Is it possible rewrite this to never use Sessions?

https://github.com/auth0/auth0-java-mvc-common/blob/master/src/main/java/com/auth0/SessionUtils.java

**Comment by hzalaz** [comment]
@AIMMOTH this is aimed for web apps mostly so storing in a session might be advisable. If you are building an API where you don't need to rely on a session, I'd recommend using https://github.com/auth0/auth0-spring-security-api.
