### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by joseeantonior** [auth0/auth0-java-mvc-common#23]
With this library, the tokens are requested internally using OkHttp but we have no way to configure the client. The builder of that client seems to be called inside AuthAPI so we don't have the option to do our own configuration or supply the library with a custom http client implementation.

We are behind a corporate proxy so we have to add the proxy configuration to the builder but this doesn't seem possible with the current implementation.

**Comment by pedes** [comment]
Hi @joseeantonior it would be a good idea to propose this feature/change-request to the other repository that owns that class, here: https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/auth/AuthAPI.java#L64

That's the main java client library from Auth0.
https://github.com/auth0/auth0-java
