### ISSUE TITLE
Need an auth0-java version 1.0.0 compatible version of this library.

### ISSUE THREAD

**Issue by mostekcm** [auth0/auth0-java-mvc-common#3]
Right now this library is dependent on 0.4.0.  For someone who also wants to use auth0-java version 1.0.0 this is not compatible with it.

**Comment by stuartstevenson** [comment]
I've just hit this issue trying to use auth0-java:1.0.0 within an app using auth0-spring-security-mvc:1.2.3. Which means I cannot use Auth0 to secure an application that I would like to use to call the Auth0 management api

**Comment by lbalmaceda** [comment]
We had our first major release some time ago, please try with that one instead.
