### ISSUE TITLE
Sessionless authorization

### ISSUE THREAD

**Issue by carl-unityworks** [auth0/auth0-java-mvc-common#56]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

I thought Auth0 promoted stateless sessions, or did I misunderstand? https://auth0.com/blog/stateless-auth-for-stateful-minds/

Still requesting sessionless/stateless version. Any hopes?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Authorization with servlet without using sessions

> A clear and concise description of what you want to happen.

Hack library 

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

You promote sessionless states

> Add any other context or screenshots about the feature request here.

https://auth0.com/blog/stateless-auth-for-stateful-minds/

**Comment by jimmyjames** [comment]
Yes, I think we should move to remove the dependency on session entirely. Currently its used for nonce/state handling, and a [relatively recent change made to support browser SameSite changes](https://github.com/auth0/auth0-java-mvc-common/pull/49) began that journey to not use sessions except as a fallback.

We would need to explore if this is something that we can do in a future minor release, or if it would be a breaking change that would need to go into the next major version. I think it's likely it would be required to go into the next major, but if there's a way to do it in a new minor to get it out sooner that would be ideal.
