### ISSUE TITLE
Using Secure Cookie flag when using 'Authorization Code Flow'

### ISSUE THREAD

**Issue by zohaibj** [auth0/auth0-java-mvc-common#58]
`TransientCookieStore` creates cookie `com.auth0.state`, but while creating this cookie Secure flag is set only if `SameSite` is `None`. But `SameSite` is always set to `Lax` in `AuthorizeUrl` build function when we use default `AuthorizationCodeFlow`. 

Is there a way to use `Secure` flag while still using default `AuthorizationCodeFlow`? 

We are running some vulnerability scans and one of the issue being highlighted is that cooking `com.auth0.state` is not secure (Testing using: User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0). 

Apologies if my understanding is not correct, we are still in the process of learning OAuth. Highly appreciate your help to point us in right direction.

**Comment by jimmyjames** [comment]
@zohaibj I've created a PR with the changes I suggested in my comment above. Would appreciate your feedback and if this would meet your requirements; it does seem to me like a good configuration option to have available. Thanks! 👍

**Comment by zohaibj** [comment]
Hi jimmyjames,

Thanks for the response. The solution you proposed above meets our requirement and should work like a charm.
 
I agree, that in this case Secure Flag does not have to be true since `responseType` does not include `id_token`. But it is one of those points which will be raised by vulnerability scans if flag of cookie is not set.

Thanks for the help, 
Appreciate it.

**Comment by jimmyjames** [comment]
Version `1.3.0` has been shipped with this change.
