### ISSUE TITLE
Sessionless version

### ISSUE THREAD

**Issue by AIMMOTH** [auth0/auth0-java-mvc-common#6]
Could you create a sessionless version with support for Servlet API 2.5?

Thank you

**Comment by shlomiken** [comment]
The current version of the library is useless to anyone trying to put more than 1 node as application (which most of us i want to hope do)
The use of session utils deep in the library - make the library not relevant for such basic deployment.
at least an option to configure the session store - so one can do that in DB or Redis.
thanks
Shlomi

**Comment by carl-unityworks** [comment]
Still request sessionless version. Any hopes?

**Comment by jimmyjames** [comment]
Hi @carl-unityworks - I know duplicating requests isn't ideal, but would you considering taking a minute and requesting this feature via our [Product Feedback](https://auth0.com/feedback) form? That will help make the feature request more visible and help drive priority. Thanks!

**Comment by carl-unityworks** [comment]
Ok sure!

**Comment by carl-unityworks** [comment]
It's submitted to ProductFeedback. Is there any updates?
