### ISSUE TITLE
Dependency missing on 1.5.0

### ISSUE THREAD

**Issue by duckranger** [auth0/auth0-java-mvc-common#77]
1.5.0 depends on com.auth0:java-jwt:3.13.0

Has this been published? Latest I can find in maven central is 3.12.1

**Comment by jimmyjames** [comment]
Looks like there was an error syncing to maven. We've resynced, and it's available in jcenter and sonatype (https://search.maven.org/artifact/com.auth0/java-jwt/3.13.0/jar),should appear in maven central soon.

**Comment by duckranger** [comment]
Thanks! can confirm maven central lists the jar :)
