### ISSUE TITLE
Directly Support Jakarta 9.1

### ISSUE THREAD

**Issue by gesker** [auth0/auth0-java-mvc-common#97]
### Describe the problem you'd like to have solved
Could this library be updated to support Jakarta 9.1 and pending version 10?

### Describe the ideal solution
Would like to use the buildAuthorizeUrl method without having to cast jakarta.servlet.http.HttpServletRequest to javax.servlet.http.HttpServletRequest and jakarta.servlet.http.HttpServletResponse to javax.servlet.http.HttpServletResponse.

### Alternatives and current work-arounds
Currently manually importing/loading the javax.servlet jar into Glassfish 6.2.2 container so that the old namespace is on the classpath of my application.

**Comment by gesker** [comment]
Thanks @jimmyjames I very much appreciate your considering this request. 

One idea that occurred to me as I began trying to use your library, and that I thought I might run past you, which would make Auth0 integration into a Jakarta application super quick and very cool would be if this library could play off of the Jakarta Security API and produce/provide annotations that could be utilized akin to DatabaseIdentityStoreDefinition & CustomFormAuthenticationMechanismDefinition -- perhaps something like Auth0IdentityStoreDefintion & Auth0FormAuthenticationMechanismDefinition, Auth0RememberMe, etc. -- which could be dropped into an ApplicationScoped bean.

Pivoting off of the Jakarta Security API would make tying an application to and using Auth0 painless - just match the parameters entered on the website and the paramaters on the annotations - and integration could be accomplished in minutes.

Let me know if you think this idea has merit. In any event... thanks again for considering my initial request.

Have a safe and fun holiday!

**Comment by uap-universe** [comment]
Jakarta EE was released more than two years ago - this library should be compatible or at least a compatible alternative should be available.

**Comment by cromat** [comment]
I have created a converter library for this purpose: [jakarta2javax](https://github.com/cromat/jakarta2javax).
